POST {{host}}/responses/400?responseBody=NO-OK
Content-Type: application/json

{
  "example-body": "hot",
  "other-values": ["cold", "excellent!"]
}

###

POST {{host}}/responses/202?responseBody=OK
Content-Type: application/xml

<request>
  <example-body>hot</example-body>
  <other-values elements="2">
      <other-value>cold</other-value>
      <other-value>excellent</other-value>
  </other-values>
</request>

###

POST {{host}}/responses/202?responseBody=OK&return400Before=2022-12-05T09%3A59%3A00%2B01%3A00
Content-Type: text/plain

Hello world!
